version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=application
      - FLASK_ENV=development
    stdin_open: true
    tty: true
    command: flask run --host=0.0.0.0
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
